--> HAND-ADDED (D-CHAPTER-PREF, S185). Not generated by drizzle-kit.
--> The re-grain from subject to chapter has NO mapping: a note written "about
--> Chemistry" names no chapter, and picking one for it would invent a claim the
--> tutor never made. So the existing rows are DROPPED, not migrated.
--> Safe to do unconditionally: 0048 (which created this table) has never
--> deployed, so PROD has no such table and no rows. The only rows that exist
--> anywhere are the 2 written by the S184 render walk on this laptop.
--> This also has to run before 0050's `ADD COLUMN chapter_id uuid NOT NULL`,
--> which would fail outright against a non-empty table.
--> ⚠️ This table has FORCE RLS, so this DELETE only sees rows if the migration
--> role bypasses it (locally `b2c` is superuser+BYPASSRLS — verified, not
--> assumed). Under a non-bypassing owner it would delete nothing; that fails
--> LOUDLY at 0050's NOT NULL rather than silently, which is the safe direction.
DELETE FROM "student_authoring_preference";--> statement-breakpoint
ALTER TABLE "student_authoring_preference" DROP CONSTRAINT "student_authoring_preference_student_id_subject_id_unique";--> statement-breakpoint
ALTER TABLE "student_authoring_preference" DROP CONSTRAINT "student_authoring_preference_subject_id_subject_id_fk";
--> statement-breakpoint
ALTER TABLE "student_authoring_preference" DROP COLUMN IF EXISTS "subject_id";