import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const b = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
await p.setViewport({ width: 1440, height: 1000 });
p.on("pageerror",e=>console.log("[pageerror]",String(e).slice(0,180)));
p.on("response", async r => { if(/trpc/.test(r.url()) && r.status()>=400){ let t=""; try{t=(await r.text()).slice(0,300);}catch{} console.log(`[HTTP ${r.status()}]`,r.url().split("/").pop().slice(0,60),t);} });
await p.goto("http://localhost:5174",{waitUntil:"networkidle2"});
await p.waitForSelector(".or-col",{timeout:20000});
await p.evaluate(()=>document.querySelector('.or-col[data-p="student"]').click());
await p.waitForSelector(".or-dev-input",{visible:true,timeout:15000});
await p.evaluate((e)=>{const el=document.querySelector(".or-dev-input");
  Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(el,e);
  el.dispatchEvent(new Event("input",{bubbles:true}));}, `dbg5-${Date.now()}@example.com`);
await p.click(".or-dev-btn");
await p.waitForSelector(".onb-root",{timeout:25000});
await new Promise(r=>setTimeout(r,3000));
await p.evaluate(()=>{const x=[...document.querySelectorAll(".onb-btn")].find(y=>/let's go|shall we|begin/i.test(y.textContent)); if(x)x.click();});
await p.waitForSelector(".onb-board",{visible:true,timeout:20000});
await new Promise(r=>setTimeout(r,1200));
await p.evaluate(()=>{const c=[...document.querySelectorAll(".onb-board")].find(x=>/cbse/i.test(x.textContent)); if(c)c.click();});
await new Promise(r=>setTimeout(r,1500));
await p.evaluate(()=>{const g=[...document.querySelectorAll(".onb-board")].find(x=>["9","10"].includes(x.textContent.trim())); if(g)g.click();});
await new Promise(r=>setTimeout(r,900));
console.log("picked so far:", await p.evaluate(()=>[...document.querySelectorAll(".is-picked")].map(e=>e.textContent.trim()||"(art)")));
await p.evaluate(()=>{const s=document.querySelector(".onb-duo-sticker"); if(s)s.click();});
await new Promise(r=>setTimeout(r,900));
console.log("picked after sticker:", await p.evaluate(()=>[...document.querySelectorAll(".is-picked")].map(e=>e.textContent.trim()||"(art)")));
console.log("CTA disabled?", await p.evaluate(()=>{const c=document.querySelector(".onb-duo-cta"); return c? c.disabled : "no cta";}));
await p.evaluate(()=>{const c=document.querySelector(".onb-duo-cta"); if(c)c.click();});
await new Promise(r=>setTimeout(r,5000));
console.log("error el:", await p.evaluate(()=>document.querySelector(".onb-error")?.textContent ?? "(none)"));
console.log("prompt now:", await p.evaluate(()=>document.querySelector(".onb-stage-prompt")?.textContent?.trim().slice(0,60)));
await b.close();
